[package]
name = "winit-ext"
version = "0.1.0"
edition = "2024"

# Example deps
[target.'cfg(not(test))'.dev-dependencies]
softbuffer = "0.4.6"

[dependencies]
# TODO: Figure out which versions of winit we are compatible with.
winit = "0.30.12"
